export const months = [
  "25-Jan", "25-Feb", "25-Mar", "25-Apr", "25-May", "25-Jun",
  "25-Jul", "25-Aug", "25-Sep", "25-Oct", "25-Nov", "25-Dec"
];

export const commissionData = [
  { shiftType: "Single Shift", commissionType: "With Basic", from: 0, to: 199.99, percentage: 0 },
  { shiftType: "Single Shift", commissionType: "With Basic", from: 200, to: 224.99, percentage: 5 },
  { shiftType: "Single Shift", commissionType: "With Basic", from: 225, to: 249.99, percentage: 10 },
  { shiftType: "Single Shift", commissionType: "With Basic", from: 250, to: 269.99, percentage: 15 },
  { shiftType: "Single Shift", commissionType: "With Basic", from: 270, to: 299.99, percentage: 20 },
  { shiftType: "Single Shift", commissionType: "With Basic", from: 300, to: 339.99, percentage: 25 },
  { shiftType: "Single Shift", commissionType: "With Basic", from: 340, to: 379.99, percentage: 30 },
  { shiftType: "Single Shift", commissionType: "With Basic", from: 380, to: Infinity, percentage: 35 },
  { shiftType: "Single Shift", commissionType: "With Out Basic", from: 0, to: 174.99, percentage: 5 },
  { shiftType: "Single Shift", commissionType: "With Out Basic", from: 175, to: 209.99, percentage: 10 },
  { shiftType: "Single Shift", commissionType: "With Out Basic", from: 210, to: 224.99, percentage: 15 },
  { shiftType: "Single Shift", commissionType: "With Out Basic", from: 225, to: 239.9, percentage: 20 },
  { shiftType: "Single Shift", commissionType: "With Out Basic", from: 240, to: 274.99, percentage: 25 },
  { shiftType: "Single Shift", commissionType: "With Out Basic", from: 275, to: 299.99, percentage: 30 },
  { shiftType: "Single Shift", commissionType: "With Out Basic", from: 300, to: 324.99, percentage: 32 },
  { shiftType: "Single Shift", commissionType: "With Out Basic", from: 325, to: 384.99, percentage: 35 },
  { shiftType: "Single Shift", commissionType: "With Out Basic", from: 385, to: Infinity, percentage: 38 },
  { shiftType: "Double Shift", commissionType: "With Basic", from: 0, to: 149.99, percentage: 0 },
  { shiftType: "Double Shift", commissionType: "With Basic", from: 150, to: 169.99, percentage: 5 },
  { shiftType: "Double Shift", commissionType: "With Basic", from: 170, to: 189.99, percentage: 10 },
  { shiftType: "Double Shift", commissionType: "With Basic", from: 190, to: 204.99, percentage: 15 },
  { shiftType: "Double Shift", commissionType: "With Basic", from: 205, to: 224.99, percentage: 20 },
  { shiftType: "Double Shift", commissionType: "With Basic", from: 225, to: 254.99, percentage: 25 },
  { shiftType: "Double Shift", commissionType: "With Basic", from: 255, to: 284.99, percentage: 30 },
  { shiftType: "Double Shift", commissionType: "With Basic", from: 285, to: Infinity, percentage: 35 },
  { shiftType: "Double Shift", commissionType: "With Out Basic", from: 0, to: 134.99, percentage: 5 },
  { shiftType: "Double Shift", commissionType: "With Out Basic", from: 135, to: 149.99, percentage: 10 },
  { shiftType: "Double Shift", commissionType: "With Out Basic", from: 150, to: 164.99, percentage: 15 },
  { shiftType: "Double Shift", commissionType: "With Out Basic", from: 165, to: 179.99, percentage: 20 },
  { shiftType: "Double Shift", commissionType: "With Out Basic", from: 180, to: 204.99, percentage: 25 },
  { shiftType: "Double Shift", commissionType: "With Out Basic", from: 205, to: 224.99, percentage: 30 },
  { shiftType: "Double Shift", commissionType: "With Out Basic", from: 225, to: 244.99, percentage: 32 },
  { shiftType: "Double Shift", commissionType: "With Out Basic", from: 245, to: 284.99, percentage: 35 },
  { shiftType: "Double Shift", commissionType: "With Out Basic", from: 285, to: Infinity, percentage: 38 },
];
